import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import { BasketCounter } from './BasketCounter'


interface NavbarLayoutProps  {
  children: React.ReactNode
}

const NavbarLayout = ({ children }: NavbarLayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-white shadow dark:bg-gray-800">
        <div className="sm:container flex items-center justify-between p-6 mx-auto text-gray-600 capitalize dark:text-gray-300">
          <div className='flex items-center justify-between'>
            <Link href="/">
              <Image className="w-auto h-6 sm:h-7" width={0} height={0} src="https://merakiui.com/images/full-logo.svg" alt="" />
            </Link>
            <Link href="/" className="text-gray-800 transition-colors duration-300 transform dark:text-gray-200  border-blue-500 mx-1.5 sm:mx-6">home</Link>
            <Link href="/About" className="text-gray-800 transition-colors duration-300 transform dark:text-gray-200  border-blue-500 mx-1.5 sm:mx-6">about</Link>
            <Link href="/Shop" className="text-gray-800 transition-colors duration-300 transform dark:text-gray-200  border-blue-500 mx-1.5 sm:mx-6">shop</Link>
          </div>
          <BasketCounter counter={3}/>
        </div>
      </nav>
      <div className="sm:container h-screen mx-auto">
        {children}
      </div>
    </>
  )
}

export default NavbarLayout